name: bdd_widget_test
description: A BDD-style widget testing library. Generates Flutter widget tests from *.feature files.
version: 0.1.6
author: Oleksandr Leuschenko <olexa.le@gmail.com>
homepage: https://github.com/olexale/bdd_widget_test

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build
  build_config:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_config
  strings: ^0.1.2
  path: ^1.7.0
  translit: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  build_runner:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_runner
  build_web_compilers:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_web_compilers
